# @package _global_
model:
  _target_: src.models.PluginNeuralConditionalDensityEstimator
  name: plugin_neural

  nuisance:
    has_prop_score: False
    hid_dim: ${model.hid_dim}
    num_epochs: 200           # n_{\text{iter,N}}

    # Tuning
    tune_hparams: False
    tune_range: 50            # number of trials for random search
    tune_type: choice

