# @package _global_
model:

  target:
    _target_: src.models.backbones.cgan.CGAN
    name: cgan

    hid_layers: ${model.nuisance.hid_layers}

    # Hparams
    gan_lat_dim: ${model.dim_out}
    gan_hid_dim: ${model.nuisance.gan_hid_dim}
    lr: 0.00005
    batch_size: 64           # batch size for the nuisance network, b_N
    noise_std_X: ${model.nuisance.noise_std_X}


exp:
  eval_criteria:
    - wass
