# @package _global_
model:

  target:
    _target_: src.models.backbones.cgan.CGAN
    name: cgan

    hid_layers: ${model.nuisance.hid_layers}

    # Hparams
    gan_hid_dim: 5
    lr: 0.0001
    batch_size: 64           # batch size for the nuisance network, b_N
    noise_std_X: ${model.nuisance.noise_std_X}


exp:
  eval_criteria:
    - wass
