# @package _global_
model:

  nuisance:
    _target_: src.models.backbones.cnf.CNFs
    name: cnf

    hid_layers: 1
    hid_layers_out: 1         # Used only for images (= CMADE)

    # Hparams
    count_bins: ???           # number of knots, n_{\text{knots}}
    noise_std_X: ???         # noise regularization for covariates, \sigma^2_x
    noise_std_Y: ???         # noise regularization for outcomes, \sigma^2_y
    lr: ???                # learning rate for the nuisance flow (CNF), \eta_\text{N}
    batch_size: ???           # batch size for the nuisance network, b_N

    hparams_grid:
      count_bins:
        - 5
        - 10
        - 20
      noise_std_X:
        - 0.0
        - 0.01
        - 0.05
        - 0.1
      noise_std_Y:
        - 0.0
        - 0.01
        - 0.05
        - 0.1
      lr:
        - 1e-3
        - 5e-3
      batch_size:
        - 32
        - 64


exp:
  eval_criteria:
    - wass
    - log_prob
