# @package _global_
model:
  nuisance:
    beta: 0.1

    vae_hid_dim: 10
    vae_lat_dim: 3
    noise_std_X: 0.05         # noise regularization for covariates, \sigma^2_x
    lr: 0.005                # learning rate for the nuisance VAE, \eta_\text{N}
    batch_size: 32           # batch size for the nuisance network, b_N

