# @package _global_
model:
  nuisance:
    beta: 1.0

    vae_hid_dim: 64
    vae_lat_dim: 50
    noise_std_X: 0.0         # noise regularization for covariates, \sigma^2_x
    lr: 0.005                # learning rate for the nuisance VAE, \eta_\text{N}
    batch_size: 32           # batch size for the nuisance network, b_N

    hparams_grid:
      vae_hid_dim:
        - 64
        - 128
      vae_lat_dim:
        - 50
        - 100
        - 150
      noise_std_X:
        - 0.0
      lr:
        - 1e-2
        - 1e-3
        - 5e-3
        - 5e-4
        - 1e-4
      batch_size:
        - 32
        - 64