# @package _global_
model:
  nuisance:
    gan_lat_dim: 150
    gan_hid_dim: 64
    noise_std_X: 0.00         # noise regularization for covariates, \sigma^2_x
    lr: 0.0001                # learning rate for the nuisance VAE, \eta_\text{N}
    batch_size: 32           # batch size for the nuisance network, b_N

    hparams_grid:
      gan_hid_dim:
        - 64
        - 128
      gan_lat_dim:
        - 50
        - 100
        - 150
        - 200
      noise_std_X:
        - 0.0
      lr:
        - 0.0001
        - 0.0005
        - 0.001
      batch_size:
        - 32
        - 64