# Dataset for training / evaluation -- specific values should be filled for each dataset
dataset:
  collection: ???                   # True for ihdp
  train_test_splitted: ???
  test_size: 0.2                    # train/test split ratio
  n_shuffle_splits: 1
  dataset_ix:                       # dataset index for ihdp

# Model specific parameters
model:
  dim_cov: ???                      # will be defined with +dataset=...
  dim_out: ???                      # will be defined with +dataset=...
  hid_dim: ???                      # will be defined with +dataset=...
  nuisance:
    tune_hparams: ???               # will be defined with +model=...
    tune_type: ???                  # will be defined with +model=...
    hparams_grid:
    tune_range:
  target:


exp:
  seed: 10
  device: cpu
  logging: True                     # Logging to MlFlow
  eval_num_mc: 200
  mlflow_uri: http://127.0.0.1:5003 # MlFlow server is located on

# Hydra defaults
defaults:
  - _self_
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog