# @package _global_
model:
  nuisance:
    beta: 1.0

    vae_hid_dim: 10
    vae_lat_dim: 3
    noise_std_X: 0.0         # noise regularization for covariates, \sigma^2_x
    lr: 0.01                # learning rate for the nuisance VAE, \eta_\text{N}
    batch_size: 64           # batch size for the nuisance network, b_N

dataset:
  n_samples: 2750
  test_size: 0.27